<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_INQUIRY</name>
   <tag></tag>
   <elementGuidId>dfb44568-b6f2-4630-ab38-1d2701b6b23e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnInquiry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnInquiry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>69d0aa0e-a033-427d-87b8-809588582c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnInquiry</value>
      <webElementGuid>75c8c365-e31a-46d7-bcbd-209d02e619de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fCallInquiry()</value>
      <webElementGuid>ab4ab114-03d5-4ed6-b4ce-660dc2dca0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnInquiry</value>
      <webElementGuid>29d990d4-e942-4e82-8ff5-08362934c70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INQUIRY</value>
      <webElementGuid>49307c73-f785-48cc-971a-3cd04a899e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnInquiry&quot;)</value>
      <webElementGuid>ba517b9a-fd28-4634-8cba-4d68b2ed583b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/QA01/iframe_Save_bizPageFrm</value>
      <webElementGuid>87975cd5-7656-434f-9858-44f31816846d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnInquiry']</value>
      <webElementGuid>f3f17640-bca7-447b-b25f-433a4f0f9231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base']/div/button</value>
      <webElementGuid>e2658c33-5d89-4f0f-9d92-7b491c789fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bucket'])[1]/following::button[1]</value>
      <webElementGuid>ebe0b040-b4e9-42dc-a8e0-c87daf27c7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Period'])[1]/following::button[1]</value>
      <webElementGuid>d24bf60d-6b46-4b9a-8919-502d1c617f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aug 2021'])[1]/preceding::button[1]</value>
      <webElementGuid>38409ee1-39b1-4c9c-a740-60b839c28c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/preceding::button[1]</value>
      <webElementGuid>6150b13a-5714-43dd-b441-8942d7e2c98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INQUIRY']/parent::*</value>
      <webElementGuid>56e52ffc-ed42-4971-bb7b-03196854c5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>71d83e40-b9ef-4261-b5e3-d48f059f36f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnInquiry' and @name = 'btnInquiry' and (text() = 'INQUIRY' or . = 'INQUIRY')]</value>
      <webElementGuid>b00b6c93-6b19-4a93-8f95-11039905bfb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
