<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FIELD</name>
   <tag></tag>
   <elementGuidId>b2216c69-8cd6-458a-a08c-6b15ce11922c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='datagrid-row-r2-2-0']/td[2]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'FIELD' or . = 'FIELD')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#datagrid-row-r2-2-0 > td:nth-of-type(2) > div.datagrid-cell.datagrid-cell-c2-CODE_NM</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e81a1899-ae46-462f-add5-e8609f8a31eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datagrid-cell datagrid-cell-c2-CODE_NM</value>
      <webElementGuid>47016b70-14fa-4906-88e4-c009bf180f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FIELD</value>
      <webElementGuid>a046bdb3-9c7d-44de-add0-62c6b42816b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datagrid-row-r2-2-0&quot;)/td[2]/div[@class=&quot;datagrid-cell datagrid-cell-c2-CODE_NM&quot;]</value>
      <webElementGuid>b3b56f88-b278-48a1-b39e-02e196944e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/QA01/iframe_Save_bizPageFrm</value>
      <webElementGuid>c397fd6a-9bba-411b-b8f6-e4530f5130a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='datagrid-row-r2-2-0']/td[2]/div</value>
      <webElementGuid>89d832a2-ca4a-4dd5-b52c-4000aa9c3d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CODE_NAME'])[1]/following::div[5]</value>
      <webElementGuid>1e77706c-c650-434f-814b-4cbc80067b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CODE'])[1]/following::div[6]</value>
      <webElementGuid>58aef5e6-cffb-42c8-9f36-bad2d157d6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DESK'])[1]/preceding::div[2]</value>
      <webElementGuid>a588470a-8635-493b-9765-4becd43525fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AGENCY'])[1]/preceding::div[4]</value>
      <webElementGuid>f406a338-a3cc-41d2-9400-3ef53fcfdc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FIELD']/parent::*</value>
      <webElementGuid>e485ed11-73f9-46c9-b45e-dbc88d5a4e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[2]/div</value>
      <webElementGuid>5d60a307-c4ff-4912-ba56-6fef46c1de4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'FIELD' or . = 'FIELD')]</value>
      <webElementGuid>f36d24cb-05b1-468b-9a05-7444ef2a6c2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
