<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inp_filterInquiry_qa01</name>
   <tag></tag>
   <elementGuidId>04d46f71-a4d5-4a15-b3e1-50aeb3d9db26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.textbox.combo.textboxfocus > input.textbox-text.validatebox-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @ref_element = 'Object Repository/tes qa01/iframe_Save_bizPageFrm (1)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b9f2c1f-c62f-4d33-ab79-681abaaa96c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>yid</name>
      <type>Main</type>
      <value>ycbtext</value>
      <webElementGuid>718f048a-3155-4c1b-ae8a-93be75d51bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8d1e2369-5004-42a2-9212-3ca75cba64e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-text validatebox-text</value>
      <webElementGuid>9a5fe5e9-b3e1-4df9-b22d-d9ef233a6c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d7dcb973-a5b2-4cd9-a573-2d8c6e51963c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>c10a5bf0-ee9f-47bc-994a-98000b0197ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inpInquiry&quot;)/div[1]/span[@class=&quot;textbox combo textboxfocus&quot;]/input[@class=&quot;textbox-text validatebox-text&quot;]</value>
      <webElementGuid>440130ac-c87b-4fbd-b2cb-880509bf614e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/QA01/iframe_Save_bizPageFrm</value>
      <webElementGuid>80afe1f5-3c29-4952-a447-8bdbc921f8c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>15e59995-881a-4422-b385-e9c0cc958d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//codecombo[@id='inpInquiry']/div/span/input</value>
      <webElementGuid>a62a6adb-9cba-48c9-9262-096b026f5088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//codecombo[2]/div/span/input</value>
      <webElementGuid>8f7343ed-041b-4678-a64b-076716f5037a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>a1e4c24f-2f75-4891-8027-6a1a6ebdceaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
