<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bucket_inpCixNo</name>
   <tag></tag>
   <elementGuidId>e4f3e1ec-c666-4c0c-94e9-dfd22b2b962f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inpCixNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inpCixNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a34dc04-4365-4d2e-9bca-f0c083a76e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>439fbff6-2a60-40f4-a70b-4af987af9817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fldname</name>
      <type>Main</type>
      <value>inpCixNo</value>
      <webElementGuid>b25c1a9e-7623-4f6a-9e27-e323caa69400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inpCixNo</value>
      <webElementGuid>0fbb4dff-de0d-42c3-952e-f78b8a11cd37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dsoname</name>
      <type>Main</type>
      <value>inpCixNo</value>
      <webElementGuid>1e52f9aa-964b-4b63-80f9-12ca0686d608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inpCixNo&quot;)</value>
      <webElementGuid>abd277fc-c8a7-4e34-8f75-72b16bcdc56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/QA01/iframe_Save_bizPageFrm</value>
      <webElementGuid>d2f8c78f-f2f4-4c0e-a543-e7fa934434c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inpCixNo']</value>
      <webElementGuid>559f614d-a71e-4b9f-9158-9c64728ebd46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='base']/div/input[2]</value>
      <webElementGuid>9d41c0cf-4ec8-444d-8ede-5090eba3fc5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input[2]</value>
      <webElementGuid>3e7a990f-f31e-4053-99ab-86e923a1454d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inpCixNo']</value>
      <webElementGuid>07df60db-041f-4233-b3bd-71a67c7e1d3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
