<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>details-button</name>
   <tag></tag>
   <elementGuidId>00cdd326-6563-43ea-aeb3-e4209ffe29ff</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'details-button' and (text() = 'Advanced' or . = 'Advanced')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#details-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='details-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7f039029-3fe0-4c7c-9ccb-05730b167ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details-button</value>
      <webElementGuid>0c854ac7-7679-44ec-9412-f228c9ac1263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>secondary-button small-link</value>
      <webElementGuid>384a0acb-6d6f-4ac0-ad57-64adb40ebb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Advanced</value>
      <webElementGuid>676bce5a-044e-44e8-a751-e6976978aafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details-button&quot;)</value>
      <webElementGuid>85771f18-38aa-4cab-89f5-92b9f5bd0aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>892d0402-df1f-4946-b450-bdc21cbc6515</webElementGuid>
   </webElementProperties>
</WebElementEntity>
