<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>proceed-link</name>
   <tag></tag>
   <elementGuidId>6c50109f-fa4d-470d-a471-da0fbc19a9d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'proceed-link' and (text() = 'Proceed to 10.25.88.76 (unsafe)' or . = 'Proceed to 10.25.88.76 (unsafe)')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#proceed-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='proceed-link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>75727ddc-6d93-45b1-98c4-d981c414c698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proceed-link</value>
      <webElementGuid>17619c8b-68ed-46ca-9435-20e124593f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>small-link</value>
      <webElementGuid>7659e0cf-2197-49f8-aa81-7f6c7fae0901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed to 10.25.88.76 (unsafe)</value>
      <webElementGuid>db1a5614-5bc2-40fa-a40c-b189849c957f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proceed-link&quot;)</value>
      <webElementGuid>d5f04ed7-72f8-4528-9739-d0951fddd2f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>/html/body/div/div[3]/p[2]/a</value>
      <webElementGuid>8928023a-0028-48e8-ae1b-edc2b2ec7e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value></value>
      <webElementGuid>7243ede4-8489-4dc3-92bd-44df9b8ecb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value></value>
      <webElementGuid>238019b6-14db-451a-bc98-40ef658d49dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
