<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hobis_loginUsername</name>
   <tag></tag>
   <elementGuidId>76de20fc-9d5c-4ab0-a452-1e079277b240</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'loginUsername' and @type = 'text' and @placeholder = 'User name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loginUsername</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginUsername']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ccd64a01-82eb-4583-9afa-1f9429044342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginUsername</value>
      <webElementGuid>bc7bcca2-bd01-4bd3-acdc-eac995e2e0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c8a955c-4167-4acc-9e11-9502d9140d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginInput</value>
      <webElementGuid>cf15fc61-02dd-4682-ad9e-307331ca831a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>a20f6bd1-5770-4186-9d40-a5f40de1d424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User name</value>
      <webElementGuid>59c8b5ad-9ccd-4582-8dbc-33093857f00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>56e29846-df18-4ab2-bb53-f8c943d0ba7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>makeUpper()</value>
      <webElementGuid>fc430b81-6753-4bb1-8825-c1be7369c249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if(event.keyCode==13) { loginPassword.focus(); return false;}</value>
      <webElementGuid>697f83f6-d1f1-47ad-becd-f2d1f949fb4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginUsername&quot;)</value>
      <webElementGuid>d31ea59a-8408-4f9a-bcac-b7ab96e948ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginUsername']</value>
      <webElementGuid>0e257c11-ef50-4905-9e74-288fa82a9336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orignalLoginDiv']/input</value>
      <webElementGuid>815a260c-8b6d-417d-b689-dc9f5e41ce09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>2252d888-3800-4edc-a7fc-f389e9699f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'loginUsername' and @type = 'text' and @placeholder = 'User name']</value>
      <webElementGuid>3357169d-89bc-4690-988c-ab53e356c391</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
