<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_CLDS</name>
   <tag></tag>
   <elementGuidId>97bd60f4-c237-4c04-bb23-857216de995c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.bptTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='bizTabTableTR']/td/div/table/tbody/tr/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>dc14ad2e-42cf-4cc2-bf0a-a8c358f62d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bptTitle</value>
      <webElementGuid>04418ae5-3f7d-4fac-91e8-521dba9d96e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CLDS</value>
      <webElementGuid>79bf3171-4af7-42c3-a891-58f66656038c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bizTabTableTR&quot;)/td[1]/div[@class=&quot;bizPageTab bptFocus&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;bptTitle&quot;]</value>
      <webElementGuid>72815f98-b759-4990-b564-807dd20ee241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='bizTabTableTR']/td/div/table/tbody/tr/td[4]</value>
      <webElementGuid>8bde5ea4-dae3-4aeb-825d-4eda635e600d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RIDWAN'])[1]/following::td[11]</value>
      <webElementGuid>4b224f3c-ca40-42f5-98dd-3872dea9269b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CL012'])[1]/following::td[12]</value>
      <webElementGuid>260d0265-ec19-4347-b4e3-e3131a3da5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::td[2]</value>
      <webElementGuid>59f4afd6-0e3b-4fc3-9995-48f78ba79eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CLDS']/parent::*</value>
      <webElementGuid>828f45fb-5542-4637-a825-1e2e60f7f340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]</value>
      <webElementGuid>92fe8e88-2856-4776-8075-c5cdd9f94522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'CLDS' or . = 'CLDS')]</value>
      <webElementGuid>4fe4faba-de11-4daf-b9c3-5e96d26418e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
