<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Inquiry noXpath</name>
   <tag></tag>
   <elementGuidId>1d376f04-6a47-4999-95c4-527ce5271d55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnInquiry']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'imgSearch' and @id = 'btnInquiry' and (text() = 'Inquiry' or . = 'Inquiry')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnInquiry</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>93a9d376-64b1-482b-9421-f85dc3626fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>L00089</value>
      <webElementGuid>7361c660-a6fa-44e9-bae4-31766de60499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>imgSearch</value>
      <webElementGuid>d4561a1d-a874-4176-88bd-c8e70ed554c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>745e299f-0641-49c6-8f7a-74618ed35cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnInquiry</value>
      <webElementGuid>b9d50d65-e095-41cd-92ed-1c265acb01cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inquiry</value>
      <webElementGuid>9a8bf03c-1c3d-47d2-9f93-72a23a2201d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnInquiry&quot;)</value>
      <webElementGuid>a898222c-9a45-4413-8ead-86691f39679e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CL01/iframe_Save_bizPageFrm noXpath</value>
      <webElementGuid>755bdc4d-7573-402b-89c2-01a18daabde8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
