<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Inquiry</name>
   <tag></tag>
   <elementGuidId>817e1063-7d1f-4180-98a2-0341001034ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnInquiry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnInquiry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>96dcd009-21a4-48dd-9037-7090de25a7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>L00089</value>
      <webElementGuid>69792e49-6325-4311-8745-b308f4602d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>imgSearch</value>
      <webElementGuid>7f12d98a-f1d1-4430-9a1f-82273c2aff9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c6da365d-2aef-428d-8d5d-e2391e507f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnInquiry</value>
      <webElementGuid>9f997295-4289-4181-9223-985b2c4bc0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inquiry</value>
      <webElementGuid>3101db5b-8d1d-4e9f-8785-165b5441b904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnInquiry&quot;)</value>
      <webElementGuid>8ca9cf89-4b09-4192-9def-c1fcdba5dae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CL01/iframe_Save_bizPageFrm</value>
      <webElementGuid>d8344763-b243-4008-9972-5c45f91f66bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnInquiry']</value>
      <webElementGuid>24a84f5f-4e6a-458f-a409-f39b9242b0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modeOFF']/div/button</value>
      <webElementGuid>fc7b9ddd-7793-4607-8729-b860edf13dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Distribute'])[1]/following::button[1]</value>
      <webElementGuid>48f1cc14-16b8-451a-a452-a9fb5b39c27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By Customer.'])[1]/following::button[1]</value>
      <webElementGuid>31fc0426-ae63-48e9-b42a-4dc127aff2fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class Type'])[1]/preceding::button[1]</value>
      <webElementGuid>ad3da4d9-3c75-407f-8137-40b020bfb6f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.'])[1]/preceding::button[1]</value>
      <webElementGuid>4ac35732-f8d9-41f2-b345-8812f9b363ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inquiry']/parent::*</value>
      <webElementGuid>4b2c3401-7163-4f22-a70f-109482cb2810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>a66ced92-dad6-486e-a4fe-d77877a20b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'imgSearch' and @id = 'btnInquiry' and (text() = 'Inquiry' or . = 'Inquiry')]</value>
      <webElementGuid>818a7a6e-77b7-42ee-8b20-ef196c86010a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
