<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Save_bizPageFrm</name>
   <tag></tag>
   <elementGuidId>fe0ae097-edc0-4f47-ab0f-bb48abf5c7e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='bizPageFrm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bizPageFrm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>bf5a6e21-00e5-46a4-b410-d9ee14564765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bizPageFrm</value>
      <webElementGuid>4e42c210-7b35-46b6-9c73-9323eb86c053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ebad457c-ecad-4bb8-be99-2e03e27db291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/biz/cl/CL01.html</value>
      <webElementGuid>50dbaff7-1a3b-410d-9c2b-defe1825e010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>subBizPageOnLoaded(this)</value>
      <webElementGuid>34a1708a-952b-431f-b0b3-8dd6949c23d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bizPageFrm&quot;)</value>
      <webElementGuid>56b38a64-4ab3-4ebb-99cb-11be9fb0992a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CL01/iframe_Close                               _12b78a</value>
      <webElementGuid>c367be44-ebda-4a68-8008-c927b80c76bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='bizPageFrm']</value>
      <webElementGuid>5e1f277b-4211-478c-a3ae-5f7d1f3e217e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bizPage']/iframe</value>
      <webElementGuid>dac1aaf6-bdee-4398-95a8-edcbafb289ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>3f9a97c4-dcdf-4341-83a7-915fddac3b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'bizPageFrm' and @src = '/biz/cl/CL01.html']</value>
      <webElementGuid>7b5a868d-7dc6-409d-9158-2c9fc5638d26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
