<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Close                               _12b78a</name>
   <tag></tag>
   <elementGuidId>b2223607-6992-4995-ab34-ae92e856d924</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.bizPageIFrame.bpDisplay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bizPageDiv']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d7ed1b7d-5b72-49f4-bbe7-41f1d357fa06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./common/subEntry.html</value>
      <webElementGuid>62eae2a8-414e-4791-91d9-4f963ff4dc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6d81c098-9e28-4238-93a9-380576555a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bizPageIFrame bpDisplay</value>
      <webElementGuid>0e7a278b-940d-4de0-8bd7-63576f6edd1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>waiFrame.__pageTabLoaded('CL01')</value>
      <webElementGuid>8ba4c495-8d1b-43b9-a1af-dac659298700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bizPageDiv&quot;)/iframe[@class=&quot;bizPageIFrame bpDisplay&quot;]</value>
      <webElementGuid>c419ea68-7fb4-49fe-a8c8-74f0f7dc38de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bizPageDiv']/iframe</value>
      <webElementGuid>18573aad-c095-4790-86d4-e9f2e41ea585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/iframe</value>
      <webElementGuid>5818e122-4205-4b75-9c6d-0786c678cce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = './common/subEntry.html']</value>
      <webElementGuid>107b3bda-1db4-40de-98b5-7cef041bb145</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
