<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Save_bizPageFrm noXpath</name>
   <tag></tag>
   <elementGuidId>b8ddd2f7-8251-4f51-b69f-0c5c1a84347a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='bizPageFrm']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'bizPageFrm' and @src = '/biz/cl/CL01.html' and @ref_element = 'Object Repository/CL01/Page_PT.KEB HANA BANK COLLECTION/iframe_Close                               _12b78a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bizPageFrm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4ad67413-423d-481d-9b26-ddeadd0db88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bizPageFrm</value>
      <webElementGuid>bb149d96-d9c1-4f43-a429-128cce418254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5f1f0c9d-fdbc-48a3-b4b2-d62191abb36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/biz/cl/CL01.html</value>
      <webElementGuid>36db68af-c6e5-406d-b89e-3f90be709463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>subBizPageOnLoaded(this)</value>
      <webElementGuid>1dc3b899-4516-490d-8b9b-400bc35b2ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bizPageFrm&quot;)</value>
      <webElementGuid>477c9124-469f-4baf-a82f-2aed4144fb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CL01/iframe_Close                               _12b78a</value>
      <webElementGuid>5b8d54bc-1254-4e5f-812e-1751b5c1757a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
