<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_By Customer_inpCust</name>
   <tag></tag>
   <elementGuidId>4735ce0a-459b-455e-af90-e75784209994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inpCust</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inpCust']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed759e65-b675-4a0f-a7a3-d9d9e5233fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89352809-f9fc-43ab-9738-3a3b211e9ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fldname</name>
      <type>Main</type>
      <value>inpCust</value>
      <webElementGuid>95f51354-778e-430a-b38f-a3a6285a9e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inpCust</value>
      <webElementGuid>2dbea4c9-94f6-4471-9523-20156db2b7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inpCust&quot;)</value>
      <webElementGuid>9f80845a-081a-4c01-80d9-203009e6c42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CL01/Page_PT.KEB HANA BANK COLLECTION/iframe_Save_bizPageFrm</value>
      <webElementGuid>0c6ed619-8657-4886-8222-096c978a1fab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inpCust']</value>
      <webElementGuid>6e3ed14c-7e6a-4afe-bf53-9b97be377ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modeOFF']/div/input[2]</value>
      <webElementGuid>c26f8772-4817-4f3b-a14b-e3c884e10758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input[2]</value>
      <webElementGuid>5a6b6cbd-d0e5-4893-b637-ec4657e9313a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inpCust']</value>
      <webElementGuid>5ca96d6f-6182-46d4-a174-e7785f45c881</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
