<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_COLLECTION_BCInp</name>
   <tag></tag>
   <elementGuidId>392bc7c9-e6c3-4054-b077-5c66f8faa290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BCInp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BCInp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73df0764-7c46-451a-8074-afddef408656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BCInp</value>
      <webElementGuid>9c11c5d7-3b00-44fb-bd16-836528793474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BizCodeInput2</value>
      <webElementGuid>3bdc0c9a-4cd8-4f3c-af07-10624791048d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10660af7-8c3c-4ccf-aa50-f3ad1f1bee26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c73e6f0b-ae41-4d92-bd0a-dc5bca122154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>BIZ</value>
      <webElementGuid>0248f3c8-66d7-4fa2-b073-2b98cb25f7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5420bcad-a916-43c4-b1b8-0a5a9bcbb72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>BCInpFocus()</value>
      <webElementGuid>e53e3182-dc0c-460e-8400-11bebd589b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>BCInpKD()</value>
      <webElementGuid>b145cd70-e953-4d71-9285-bfedf894c60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>BCInpKU()</value>
      <webElementGuid>8933f945-031c-4118-b9e4-812b3862d4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>BCInpKP()</value>
      <webElementGuid>50494d4f-9545-43c5-a512-3cdf6f6051ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BCInp&quot;)</value>
      <webElementGuid>0d11e6d2-d9dd-487b-9992-e0b76beeaec3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BCInp']</value>
      <webElementGuid>3142c943-4648-42fe-8e4a-e2a3ad963f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='frameRootTable']/tbody/tr/td/div/table/tbody/tr/td[2]/div/table/tbody/tr/td/table/tbody/tr/td/div/input</value>
      <webElementGuid>861f0b07-e556-416d-bac7-760d8fb814a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>71331a77-4261-402e-bfbb-ec4831cafe49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'BCInp' and @type = 'text' and @placeholder = 'BIZ']</value>
      <webElementGuid>cac13fce-9ce2-4337-ab32-cd8aeaa5c7dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
