<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Close                               _12b78a (1)</name>
   <tag></tag>
   <elementGuidId>f729a5d7-bcdb-4c8f-b40c-cb04606d13d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.bizPageIFrame.bpDisplay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bizPageDiv']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b11c1bdd-a9b3-4c6c-ba65-b4787bb9fabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./common/subEntry.html</value>
      <webElementGuid>b3bf6b06-2379-41cb-a96b-5e100c000a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>99fb03f4-777e-4b50-abe2-f989bdfee2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bizPageIFrame bpDisplay</value>
      <webElementGuid>a0fac06e-b25c-4a13-8951-0866be32b9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>waiFrame.__pageTabLoaded('QA01')</value>
      <webElementGuid>c9694050-18c8-4ebe-b905-b740ad60bfc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bizPageDiv&quot;)/iframe[@class=&quot;bizPageIFrame bpDisplay&quot;]</value>
      <webElementGuid>aefa33a1-b92f-4507-a380-b3e952884d2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bizPageDiv']/iframe</value>
      <webElementGuid>bca63f45-3a89-4d97-9ff5-a29a8a890cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/iframe</value>
      <webElementGuid>ada7cefc-8e30-4455-89f9-f77846f17453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = './common/subEntry.html']</value>
      <webElementGuid>647b57d2-4791-4bb4-b6ab-7894abf24837</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
