<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Save_bizPageFrm (1)</name>
   <tag></tag>
   <elementGuidId>46876165-2b72-4b7a-a93d-ef520e4ee204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bizPageFrm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='bizPageFrm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>df3a6738-0508-49a2-af3f-9daf4d797ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bizPageFrm</value>
      <webElementGuid>ac1c28bc-5206-4db7-9b25-b8c6199cc531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f598140f-e70d-479b-b0fc-af803a7cf15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/biz/qa/QA01.html</value>
      <webElementGuid>fac24e13-48fe-4d64-b389-0e4145a81633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>subBizPageOnLoaded(this)</value>
      <webElementGuid>ba4e1f1a-b9c1-4eb6-a6e5-47f5d9bba386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bizPageFrm&quot;)</value>
      <webElementGuid>817a9b7a-767a-454f-9cde-63ed2736f6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/tes qa01/iframe_Close                               _12b78a</value>
      <webElementGuid>8fddf9c3-45e1-4617-b664-b3296410da0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='bizPageFrm']</value>
      <webElementGuid>8b00383e-4486-43a0-981c-636381d48cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bizPage']/iframe</value>
      <webElementGuid>57c986ee-0c27-4129-b014-e9a827f32213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>fe405f22-7729-40fb-91a2-3351192af17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'bizPageFrm' and @src = '/biz/qa/QA01.html']</value>
      <webElementGuid>87852002-135c-4fe4-9cf7-9bfcb717bb04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
