<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Save_bizPageFrm</name>
   <tag></tag>
   <elementGuidId>c996857f-dd94-462c-9339-d9f5db968152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bizPageFrm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='bizPageFrm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c97bcc89-e5b3-4bb8-8df2-67778341018f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bizPageFrm</value>
      <webElementGuid>a46416e2-6a60-4f32-9fb1-3493d8e99055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9b8ae8cb-2f5a-4380-8e56-46dd8e4a9f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/biz/qa/QA01.html</value>
      <webElementGuid>d9dbfc50-209a-45ab-b885-25393672a98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>subBizPageOnLoaded(this)</value>
      <webElementGuid>3b511535-52a8-46d1-8110-4504c122fa0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bizPageFrm&quot;)</value>
      <webElementGuid>702f266b-0ec1-4a10-b80e-ec9943866ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/QA01/iframe_Close                               _12b78a</value>
      <webElementGuid>048d9f09-9594-46a7-9257-0416b4512977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/tes qa01/iframe_Close                               _12b78a</value>
      <webElementGuid>133d81b7-6551-4141-b628-6b105b0bcdfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='bizPageFrm']</value>
      <webElementGuid>69662c7a-af74-4e5d-998c-cce7ee35b2a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bizPage']/iframe</value>
      <webElementGuid>90d421d6-d84d-4a0f-a5e5-48c5f488adf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>ae35fca0-8409-486c-b695-73de181f10d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'bizPageFrm' and @src = '/biz/qa/QA01.html']</value>
      <webElementGuid>06749640-68e6-4f63-9258-f41d53864b9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
