<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inp_endPeriod - Copy</name>
   <tag></tag>
   <elementGuidId>230655c0-1967-4b11-9fd9-5b0fb4cbba1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @ref_element = 'Object Repository/tes qa01/iframe_Save_bizPageFrm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inpPeriodEndDt > span.dateeditBox > div.calbtnSpan > input.calbtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da2066db-803a-4108-b4cc-7f1688306c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>yid</name>
      <type>Main</type>
      <value>calbtn</value>
      <webElementGuid>ce2fa101-4d1f-4538-9b90-5fe8a1cab512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f96c94c7-77c2-4853-b2ba-3e509dd8178a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calbtn</value>
      <webElementGuid>a536131b-0003-43fb-b729-7abaf1801758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inpPeriodEndDt&quot;)/span[@class=&quot;dateeditBox&quot;]/div[@class=&quot;calbtnSpan&quot;]/input[@class=&quot;calbtn&quot;]</value>
      <webElementGuid>3dc746f9-b074-4521-902b-86a530f44e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/tes qa01/iframe_Save_bizPageFrm</value>
      <webElementGuid>c9dad213-d04f-43e8-826d-f52d4375a876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='button'])[2]</value>
      <webElementGuid>6eadd9bb-ef00-4aee-9454-a0aec3d0b0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dateedit[@id='inpPeriodEndDt']/span/div/input</value>
      <webElementGuid>5221bbe5-3cb6-42d8-99c0-80bbc01e0d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/input</value>
      <webElementGuid>52f96a3d-c5c8-44d1-a0c1-5a2e5eba33f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>c70bfa25-779c-41ae-a279-c71eb22448fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
