<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inp_endPeriod</name>
   <tag></tag>
   <elementGuidId>892c59e3-fa69-4448-8bbd-4bfd30cd2a69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @ref_element = 'Object Repository/tes qa01/iframe_Save_bizPageFrm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inpPeriodEndDt > span.dateeditBox > div.calbtnSpan > input.calbtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b6eaf66-3ba9-4c53-9652-e7ca15762925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>yid</name>
      <type>Main</type>
      <value>calbtn</value>
      <webElementGuid>8754bfb7-0323-4a03-bfc5-6c8793148066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>757caeea-6358-4277-bc1c-4dd95800db74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calbtn</value>
      <webElementGuid>45383c1c-002e-4b25-8667-25a647729f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inpPeriodEndDt&quot;)/span[@class=&quot;dateeditBox&quot;]/div[@class=&quot;calbtnSpan&quot;]/input[@class=&quot;calbtn&quot;]</value>
      <webElementGuid>d73a44ef-ead5-4407-bf34-311e4d7cedf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/tes qa01/iframe_Save_bizPageFrm</value>
      <webElementGuid>9b788ebf-568b-4bfc-bbc5-553d9d36f26d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='button'])[3]</value>
      <webElementGuid>84ee0099-8a31-4d40-8ad0-a3dad550327e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dateedit[@id='inpPeriodEndDt']/span/div/input</value>
      <webElementGuid>dcda35f8-3916-4fb1-baa7-7963a6dd093d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dateedit[2]/span/div/input</value>
      <webElementGuid>59785c3e-9f36-44f6-828c-aa774846d310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>c5fadcbb-cfc9-464b-afc8-93e8e3027ff4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
