<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inp_startperiod</name>
   <tag></tag>
   <elementGuidId>9d4067b0-3137-4f4d-8447-da1166fd15c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.calbtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61ca0d93-21db-4152-a7b0-0f4f575e657a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>yid</name>
      <type>Main</type>
      <value>calbtn</value>
      <webElementGuid>0a44c3c5-e610-4660-8a2c-ff3c85300330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a207a2d0-356d-48f2-b5e7-778b7da9277a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calbtn</value>
      <webElementGuid>0545257a-308c-4bc6-9546-1a904573c84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inpPeriodStartDt&quot;)/span[@class=&quot;dateeditBox&quot;]/div[@class=&quot;calbtnSpan&quot;]/input[@class=&quot;calbtn&quot;]</value>
      <webElementGuid>cc18afcb-8957-434b-aafa-285aa1e814b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/QA01/iframe_Save_bizPageFrm</value>
      <webElementGuid>18ae355f-28a2-4636-b441-b3b913ba6f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/tes qa01/iframe_Save_bizPageFrm</value>
      <webElementGuid>c9357b86-dfd8-4dc5-bf04-1c6d1d0b71dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='button'])[2]</value>
      <webElementGuid>c8a788f1-832f-43ec-b382-f0c4de91c5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dateedit[@id='inpPeriodStartDt']/span/div/input</value>
      <webElementGuid>7a7de0ed-f3b2-4bcb-b61e-3ffbcc292021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/input</value>
      <webElementGuid>3b0b68ac-b524-429f-a153-e5e2f72e2b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>f626900c-9197-4dc0-91b2-dc788b23c8b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
