<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_5</name>
   <tag></tag>
   <elementGuidId>3f925ed4-e6f3-4933-81e2-52877e12bce7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.calendar-day.calendar-nav-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//dateedit[@id='inpPeriodEndDt']/div/div[2]/table/tbody/tr[2]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b37ec765-b197-4ca3-b70e-1722555a329f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calendar-day  calendar-nav-hover</value>
      <webElementGuid>364bac00-e4aa-47ee-acb4-ffdbbf67c02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>abbr</name>
      <type>Main</type>
      <value>2024,8,5</value>
      <webElementGuid>253c6617-b953-46fe-854f-9c9ee742091d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>9d1c2c02-4167-4a90-b5ad-f1eb4b5c5aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inpPeriodEndDt&quot;)/div[@class=&quot;calendar&quot;]/div[@class=&quot;calendar-body&quot;]/table[@class=&quot;calendar-dtable&quot;]/tbody[1]/tr[2]/td[@class=&quot;calendar-day  calendar-nav-hover&quot;]</value>
      <webElementGuid>ccdea5d8-8b60-4d4e-ac72-6b49b7ced110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/tes qa01/iframe_Save_bizPageFrm</value>
      <webElementGuid>26ea664f-b673-48a5-a65d-2581deb310d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dateedit[@id='inpPeriodEndDt']/div/div[2]/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>e315cbdf-9f3b-4fb0-87b2-eafadcde091c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::td[9]</value>
      <webElementGuid>8f6ababc-e660-4e87-af42-aa1668f79d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[1]/following::td[9]</value>
      <webElementGuid>6ab85470-2079-4189-998d-9f05e92183db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::td[34]</value>
      <webElementGuid>f3196097-a780-4411-b743-2cb1a6bd7424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::td[35]</value>
      <webElementGuid>9896b80c-aac9-48fd-9603-0b3da617434b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5']/parent::*</value>
      <webElementGuid>dc8bd29b-562c-4de7-8cce-c5a7cd9e998b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]</value>
      <webElementGuid>cf2fa431-193a-46d6-9c67-50133614cb12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '5' or . = '5')]</value>
      <webElementGuid>3c30d3e2-74bf-4fd7-b4f5-c81ef80ed874</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
